# Generated by Django 4.0.6 on 2022-07-27 14:44

from django.db import migrations, models
import django.db.models.deletion
import lb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('votes', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar', models.TextField(null=True)),
                ('time', models.FloatField(default=lb.models.get_time)),
                ('score', models.IntegerField()),
                ('subs', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.user')),
            ],
            options={
                'unique_together': {('user', 'time')},
            },
        ),
    ]
